debug: true
addr: "0.0.0.0:9091"
db:
  dsn: "psd:mysql_password@tcp(mysql:3306)/power_supply_db?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
  max_idle_conns: 2
  max_open_conns: 10
  conn_max_lifetime: 3600
jwt:
  secret: "test-secret-key"
  expire_hours: 24
log:
  level: "debug"
  file_path: "./logs/app_test.log"
server:
  read_timeout: 10
  write_timeout: 10
  idle_timeout: 60
