debug: true
addr: "0.0.0.0:9090"
db:
  dsn: "psd:mysql_password@tcp(mysql:3306)/power_supply_db?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
  max_idle_conns: 5
  max_open_conns: 50
  conn_max_lifetime: 3600
jwt:
  secret: "dev-secret-key-change-in-production"
  expire_hours: 72
log:
  level: "debug"
  file_path: "./logs/app_dev.log"
