debug: false
addr: "0.0.0.0:8080"
db:
  dsn: "your_prod_user:your_prod_password@tcp(your_prod_host:3306)/your_prod_db?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
jwt:
  secret: "your-production-secret-key"
  expire_hours: 24
log:
  level: "info"
  file_path: "./logs/app.log"
